/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UsersAddUserImport } from './routes/users/add-user'
import { Route as UsersIdImport } from './routes/users/$id'
import { Route as TableUserTableImport } from './routes/table/user-table'
import { Route as LoginLoginUserImport } from './routes/login/login-user'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersAddUserRoute = UsersAddUserImport.update({
  id: '/users/add-user',
  path: '/users/add-user',
  getParentRoute: () => rootRoute,
} as any)

const UsersIdRoute = UsersIdImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRoute,
} as any)

const TableUserTableRoute = TableUserTableImport.update({
  id: '/table/user-table',
  path: '/table/user-table',
  getParentRoute: () => rootRoute,
} as any)

const LoginLoginUserRoute = LoginLoginUserImport.update({
  id: '/login/login-user',
  path: '/login/login-user',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login/login-user': {
      id: '/login/login-user'
      path: '/login/login-user'
      fullPath: '/login/login-user'
      preLoaderRoute: typeof LoginLoginUserImport
      parentRoute: typeof rootRoute
    }
    '/table/user-table': {
      id: '/table/user-table'
      path: '/table/user-table'
      fullPath: '/table/user-table'
      preLoaderRoute: typeof TableUserTableImport
      parentRoute: typeof rootRoute
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdImport
      parentRoute: typeof rootRoute
    }
    '/users/add-user': {
      id: '/users/add-user'
      path: '/users/add-user'
      fullPath: '/users/add-user'
      preLoaderRoute: typeof UsersAddUserImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/login-user': typeof LoginLoginUserRoute
  '/table/user-table': typeof TableUserTableRoute
  '/users/$id': typeof UsersIdRoute
  '/users/add-user': typeof UsersAddUserRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login/login-user': typeof LoginLoginUserRoute
  '/table/user-table': typeof TableUserTableRoute
  '/users/$id': typeof UsersIdRoute
  '/users/add-user': typeof UsersAddUserRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login/login-user': typeof LoginLoginUserRoute
  '/table/user-table': typeof TableUserTableRoute
  '/users/$id': typeof UsersIdRoute
  '/users/add-user': typeof UsersAddUserRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/login-user'
    | '/table/user-table'
    | '/users/$id'
    | '/users/add-user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login/login-user'
    | '/table/user-table'
    | '/users/$id'
    | '/users/add-user'
  id:
    | '__root__'
    | '/'
    | '/login/login-user'
    | '/table/user-table'
    | '/users/$id'
    | '/users/add-user'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginLoginUserRoute: typeof LoginLoginUserRoute
  TableUserTableRoute: typeof TableUserTableRoute
  UsersIdRoute: typeof UsersIdRoute
  UsersAddUserRoute: typeof UsersAddUserRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginLoginUserRoute: LoginLoginUserRoute,
  TableUserTableRoute: TableUserTableRoute,
  UsersIdRoute: UsersIdRoute,
  UsersAddUserRoute: UsersAddUserRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login/login-user",
        "/table/user-table",
        "/users/$id",
        "/users/add-user"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login/login-user": {
      "filePath": "login/login-user.tsx"
    },
    "/table/user-table": {
      "filePath": "table/user-table.tsx"
    },
    "/users/$id": {
      "filePath": "users/$id.tsx"
    },
    "/users/add-user": {
      "filePath": "users/add-user.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
