/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UsersAddUserImport } from './routes/users/add-user'
import { Route as TableUserListImport } from './routes/table/user-list'
import { Route as ProfileIdImport } from './routes/profile/$id'
import { Route as CommitGetCommitImport } from './routes/commit/get-commit'
import { Route as CommitAddTempImport } from './routes/commit/add-temp'
import { Route as CommitAddCommitsImport } from './routes/commit/add-commits'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersAddUserRoute = UsersAddUserImport.update({
  id: '/users/add-user',
  path: '/users/add-user',
  getParentRoute: () => rootRoute,
} as any)

const TableUserListRoute = TableUserListImport.update({
  id: '/table/user-list',
  path: '/table/user-list',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIdRoute = ProfileIdImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRoute,
} as any)

const CommitGetCommitRoute = CommitGetCommitImport.update({
  id: '/commit/get-commit',
  path: '/commit/get-commit',
  getParentRoute: () => rootRoute,
} as any)

const CommitAddTempRoute = CommitAddTempImport.update({
  id: '/commit/add-temp',
  path: '/commit/add-temp',
  getParentRoute: () => rootRoute,
} as any)

const CommitAddCommitsRoute = CommitAddCommitsImport.update({
  id: '/commit/add-commits',
  path: '/commit/add-commits',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/commit/add-commits': {
      id: '/commit/add-commits'
      path: '/commit/add-commits'
      fullPath: '/commit/add-commits'
      preLoaderRoute: typeof CommitAddCommitsImport
      parentRoute: typeof rootRoute
    }
    '/commit/add-temp': {
      id: '/commit/add-temp'
      path: '/commit/add-temp'
      fullPath: '/commit/add-temp'
      preLoaderRoute: typeof CommitAddTempImport
      parentRoute: typeof rootRoute
    }
    '/commit/get-commit': {
      id: '/commit/get-commit'
      path: '/commit/get-commit'
      fullPath: '/commit/get-commit'
      preLoaderRoute: typeof CommitGetCommitImport
      parentRoute: typeof rootRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdImport
      parentRoute: typeof rootRoute
    }
    '/table/user-list': {
      id: '/table/user-list'
      path: '/table/user-list'
      fullPath: '/table/user-list'
      preLoaderRoute: typeof TableUserListImport
      parentRoute: typeof rootRoute
    }
    '/users/add-user': {
      id: '/users/add-user'
      path: '/users/add-user'
      fullPath: '/users/add-user'
      preLoaderRoute: typeof UsersAddUserImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commit/add-commits': typeof CommitAddCommitsRoute
  '/commit/add-temp': typeof CommitAddTempRoute
  '/commit/get-commit': typeof CommitGetCommitRoute
  '/profile/$id': typeof ProfileIdRoute
  '/table/user-list': typeof TableUserListRoute
  '/users/add-user': typeof UsersAddUserRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commit/add-commits': typeof CommitAddCommitsRoute
  '/commit/add-temp': typeof CommitAddTempRoute
  '/commit/get-commit': typeof CommitGetCommitRoute
  '/profile/$id': typeof ProfileIdRoute
  '/table/user-list': typeof TableUserListRoute
  '/users/add-user': typeof UsersAddUserRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/commit/add-commits': typeof CommitAddCommitsRoute
  '/commit/add-temp': typeof CommitAddTempRoute
  '/commit/get-commit': typeof CommitGetCommitRoute
  '/profile/$id': typeof ProfileIdRoute
  '/table/user-list': typeof TableUserListRoute
  '/users/add-user': typeof UsersAddUserRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commit/add-commits'
    | '/commit/add-temp'
    | '/commit/get-commit'
    | '/profile/$id'
    | '/table/user-list'
    | '/users/add-user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commit/add-commits'
    | '/commit/add-temp'
    | '/commit/get-commit'
    | '/profile/$id'
    | '/table/user-list'
    | '/users/add-user'
  id:
    | '__root__'
    | '/'
    | '/commit/add-commits'
    | '/commit/add-temp'
    | '/commit/get-commit'
    | '/profile/$id'
    | '/table/user-list'
    | '/users/add-user'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommitAddCommitsRoute: typeof CommitAddCommitsRoute
  CommitAddTempRoute: typeof CommitAddTempRoute
  CommitGetCommitRoute: typeof CommitGetCommitRoute
  ProfileIdRoute: typeof ProfileIdRoute
  TableUserListRoute: typeof TableUserListRoute
  UsersAddUserRoute: typeof UsersAddUserRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommitAddCommitsRoute: CommitAddCommitsRoute,
  CommitAddTempRoute: CommitAddTempRoute,
  CommitGetCommitRoute: CommitGetCommitRoute,
  ProfileIdRoute: ProfileIdRoute,
  TableUserListRoute: TableUserListRoute,
  UsersAddUserRoute: UsersAddUserRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/commit/add-commits",
        "/commit/add-temp",
        "/commit/get-commit",
        "/profile/$id",
        "/table/user-list",
        "/users/add-user"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/commit/add-commits": {
      "filePath": "commit/add-commits.tsx"
    },
    "/commit/add-temp": {
      "filePath": "commit/add-temp.tsx"
    },
    "/commit/get-commit": {
      "filePath": "commit/get-commit.tsx"
    },
    "/profile/$id": {
      "filePath": "profile/$id.tsx"
    },
    "/table/user-list": {
      "filePath": "table/user-list.tsx"
    },
    "/users/add-user": {
      "filePath": "users/add-user.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
